import jsPDF from "jspdf";
import formatRupiah from "./rupiahFormat";

function exportPDF(totalRevenue, totalOrders, totalProducts, totalUsers) {
  const doc = new jsPDF();

  // Header
  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.text("Laporan Dashboard Owner", 20, 20);

  // Date
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(`Tanggal: ${new Date().toLocaleDateString("id-ID")}`, 20, 30);

  // Line separator
  doc.setLineWidth(0.5);
  doc.line(20, 35, 190, 35);

  // Content
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("Ringkasan Data:", 20, 45);

  doc.setFont("helvetica", "normal");
  let yPosition = 55;

  doc.text(
    `Total Revenue: Rp ${formatRupiah(totalRevenue)}`,
    30,
    yPosition
  );
  yPosition += 10;

  doc.text(`Total Orders: ${totalOrders}`, 30, yPosition);
  yPosition += 10;

  doc.text(`Total Products: ${totalProducts}`, 30, yPosition);
  yPosition += 10;

  doc.text(`Total Customer Active: ${totalUsers}`, 30, yPosition);
  yPosition += 10;

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(128, 128, 128);
  doc.text("Generated by ReuseMart Dashboard", 20, 280);

  // Save
  doc.save(`laporan-dashboard-${new Date().getTime()}.pdf`);
}

export default exportPDF;
